spring:
  application:
    name: appointment-search-service
  profiles:
    default: api
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@localhost:27017/appointment_search?authSource=admin}
      database: ${SPRING_DATA_MONGODB_DATABASE:appointment_search}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:appointment-search-service}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
app:
  kafka:
    topics:
      appointment-scheduled: scheduling.appointment.scheduled

management:
  health:
    mongo:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info
