spring:
  application:
    name: appointment-search-service
  profiles:
    default: api
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:appointment-search-service}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@localhost:27017/appointment_search?authSource=admin}
app:
  kafka:
    topics:
      appointment-scheduled: scheduling.appointment.scheduled

management:
  health:
    mongodb:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
