spring:
  application:
    name: appointment-search-service
  profiles:
    default: api
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@localhost:27017/appointment_search?authSource=admin}

management:
  health:
    mongodb:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
